// <auto-generated />
using HardwareListAPI.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HardwareListAPI.Migrations
{
    [DbContext(typeof(HardwareDBContext))]
    partial class HardwareDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("HardwareListAPI.Models.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CinebenchMultiCore");

                    b.Property<int>("CinebenchSingleCore");

                    b.Property<int>("Frequency");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<string>("Vendor")
                        .IsRequired();

                    b.Property<float>("Voltage");

                    b.HasKey("Id");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("HardwareListAPI.Models.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CoreClock");

                    b.Property<int>("FireStrikeScore");

                    b.Property<int>("MemoryClock");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<string>("Vendor")
                        .IsRequired();

                    b.Property<float>("Voltage");

                    b.HasKey("Id");

                    b.ToTable("GPUs");
                });

            modelBuilder.Entity("HardwareListAPI.Models.HDD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AccessTime");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<double>("Random4K");

                    b.Property<double>("TransferRate");

                    b.Property<string>("Vendor")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("HDDs");
                });

            modelBuilder.Entity("HardwareListAPI.Models.SSD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AccessTime");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<double>("Random4K");

                    b.Property<double>("TransferRate");

                    b.Property<string>("Vendor")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SSDs");
                });
#pragma warning restore 612, 618
        }
    }
}
